language: python
python: '3.5'
install:
  - pip install -r requirements.txt
script:
  - python setup.py test
before_deploy:
  - sed -e "s/^\(__version__ = '[0-9]\.[0-9]\)\.dev/\1b$TRAVIS_BUILD_NUMBER/g" pch2csd/__init__.py > pch2csd/__init__.py
deploy:
  provider: pypi
  user: ech
  password:
    secure: "iPqrqygnaNxc+j2xAoXqm6zOWtzUxeuCmMpF7yDNpJMyIAW/d7BJ7hAbH6i3wm+Uidi0o+NK6icbBPhPUaHZ/60B0fUMnNU6t1ADeZAv+rIJmJjjypmGG79VvhngmKIPKOhWF5Oqj4ZdYJSgTqlj9igaRZjobMtq+tzT26QZ+Vw7HLD7SqCT5e3Dk5uY1n5WCtMNZCTnlEEWa54uCA5acXJzq/Y63b5eL6JQD8IKtqosygwJaJEhmfUcS38dmI9aGOP/gvgGiv9H+gj+c53WtD3MLxDn6HmRnvc69+Nfv5D+kY971cniGP9pQkhTOBqYcI3FQYadoyGTWDvq8yjCNQEJo/N/OTUd/SL1PlC0M2qUS7UBMZs27lEeeVd4FEn8LarOPRkRc/+zExLtqZhJ1UR1FSLdNfWcbLvm+Qa4yFmr6CjukGLX/WFEVL0NojQbagx+cBhRyj6CDPztvG3L0mkXFcRUxgF58RgrDTY6L8qjUc3Uj8kFxXSnftSDYN2BPcmkIq/NFBE0IirpEpwBxTvZq3tYauTAU0DJbUIl2fFHeJUmqGhYin+bSjKWqVxaqKNsZ0YTU9uoC9BeP+NYUhIO6SAjqL21GfxLKu+F2lBWXemSIdkYxdbX2crg3X2o0Eeobf9Kk1d6wQbuFFMfUsT3603NpExRe/71tmSRjmo="
  distributions: sdist bdist_wheel

